# Generated by Django 3.2.11 on 2022-05-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Team_id')),
                ('Team_Name', models.CharField(db_index=True, max_length=20, verbose_name='Team Name')),
                ('City', models.CharField(max_length=35, verbose_name='City')),
                ('Area', models.CharField(max_length=5, verbose_name='Area')),
                ('Coach_Name', models.CharField(max_length=35, verbose_name='Coach')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('Stadium_ID', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Stadium_ID')),
                ('Stadium_Name', models.CharField(max_length=50, verbose_name='Stadium Name')),
                ('Location', models.CharField(max_length=50, verbose_name='Location')),
                ('Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.team')),
            ],
            options={
                'verbose_name': 'Stadium_ID',
                'verbose_name_plural': 'Stadium_ID',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Player_ID', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Player_id')),
                ('Player_Name', models.CharField(db_index=True, max_length=35, verbose_name='Player Name')),
                ('Avg_Point', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Point')),
                ('Avg_Rebound', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Rebound')),
                ('Avg_Assist', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Assist')),
                ('Avg_Steal', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Steal')),
                ('Avg_Block', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Block')),
                ('Avg_Trunover', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Trunover')),
                ('Avg_Foul', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Avg_Foul')),
                ('p3Per', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='3point%')),
                ('p2Per', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='2point%')),
                ('freeThrowPer', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='freeThrow%')),
                ('Position', models.CharField(db_index=True, max_length=15, verbose_name='Position')),
                ('SALARY', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='SALARY')),
                ('Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.team')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coach',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('Game_ID', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Player_id')),
                ('Score', models.CharField(max_length=10, verbose_name='Score')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Away_Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Away_Team', to='DB_Models.team')),
                ('Home_Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_Team', to='DB_Models.team')),
                ('Stadium_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.stadium')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('Coach_ID', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Coach_id')),
                ('Coach_Name', models.CharField(db_index=True, max_length=35, verbose_name='Coach Name')),
                ('Num_of_Champ', models.IntegerField(default=0, verbose_name='Num_of_Champ')),
                ('SALARY', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='SALARY')),
                ('Year_Start', models.DateField(verbose_name='Coach year start')),
                ('Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.team')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coach',
            },
        ),
    ]
