# Generated by Django 3.2.11 on 2022-05-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Team_ID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Team_Name'),
        ),
    ]
