# Generated by Django 3.2.11 on 2022-05-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_Models', '0002_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='Team_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.team', verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Team_ID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Team_ID'),
        ),
    ]
