# Generated by Django 3.2.11 on 2022-05-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_Models', '0003_auto_20220506_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'verbose_name': 'Stadium', 'verbose_name_plural': 'Stadium'},
        ),
        migrations.AlterField(
            model_name='game',
            name='Away_Team_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Away_Team', to='DB_Models.team', verbose_name='Away_Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='Game_ID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Game_id'),
        ),
        migrations.AlterField(
            model_name='game',
            name='Home_Team_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_Team', to='DB_Models.team', verbose_name='Home_Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='Stadium_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.stadium', verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='player',
            name='SALARY',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='SALARY(/10000 dollars)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Team_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p2Per',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='shoot%'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='Team_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_Models.team', verbose_name='Team'),
        ),
    ]
